spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:~/order-system;MODE=MySQL
    username: sa
    password:

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6379
      repositories:
        enabled: false
