### 1.상품 생성
POST http://localhost:8080/api/stock
Content-Type: application/json

{
  "stockName": "의자",
  "price": 10000.0,
  "quantity": 20,
  "categoryId": 5
}

### 2.상품 조회
GET http://localhost:8080/api/stocks?categoryId=1&stockName="의자"
Content-Type: application/json

### 3.상품 수정
PUT http://localhost:8080/api/stock/1
Content-Type: application/json

{
  "id": 1,
  "name": "책상",
  "price": 12000.0,
  "quantity": 10,
  "categoryId": 1
}

### 4.상품 삭제
DELETE http://localhost:8080/api/stock/1
Content-Type: application/json
