name: BE - CI(Init repo -> CI Gradle Cache -> Test)

on:
  pull_request:
    branches: [main]
    paths:
      [
        "src/**",
        "pom.xml",
      ]
    types: [opened, synchronize, reopened]

defaults:
  run:
    working-directory: ./

permissions:
  contents: read

jobs:
  be-test:
    name: Test SpringBoot
    runs-on: ubuntu-20.04

    steps:
      - name: setup repo
        uses: actions/checkout@v3

      - name: setup java 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "adopt"
          cache: maven

      - name: Use Maven cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.maven/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Test And Analyze
        run: mvn test
